ALTER TYPE "MapElementType" ADD VALUE IF NOT EXISTS 'ROLLER_SHUTTER';
ALTER TYPE "MapElementType" ADD VALUE IF NOT EXISTS 'SINGLE_DOOR';
ALTER TYPE "MapElementType" ADD VALUE IF NOT EXISTS 'DOUBLE_DOOR';
ALTER TYPE "MapElementType" ADD VALUE IF NOT EXISTS 'STAIRS';
ALTER TYPE "MapElementType" ADD VALUE IF NOT EXISTS 'LIFT';
ALTER TYPE "MapElementType" ADD VALUE IF NOT EXISTS 'TABLE';
ALTER TYPE "MapElementType" ADD VALUE IF NOT EXISTS 'CHAIR';
ALTER TYPE "MapElementType" ADD VALUE IF NOT EXISTS 'CUPBOARD';
