"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Box, DoorOpen, Grid3X3, MousePointer2, Plus, Save, SquareDashed, Tag, Trash2, Type, Warehouse, X, ZoomIn, ZoomOut } from "lucide-react";
import { PageHeader } from "@/components/page-header";

type UnitType = { id: string; name: string; widthMetres: string | null; lengthMetres: string | null; areaSqMetres: string | null };
type Unit = { id: string; number: string; status: string; monthlyRate: string; unitTypeId: string; unitType: UnitType };
type SavedElement = { id: string; unitId: string | null; type: ElementType; x: number; y: number; width: number; height: number; rotation: number; label: string | null; unit: Unit | null };
type MapRecord = { id: string; name: string; width: number; height: number; elements: SavedElement[] };
type Facility = { id: string; name: string; code: string; unitTypes: UnitType[]; units: Unit[]; maps: MapRecord[] };
type ElementType = "UNIT" | "ZONE" | "WALL" | "DOOR" | "LABEL";
type DraftUnit = { unitTypeId: string; number: string; floor?: string; zone?: string; monthlyRate: number; taxRate: number };
type CanvasElement = { id: string; unitId?: string; type: ElementType; x: number; y: number; width: number; height: number; rotation: number; label: string; status?: string; unit?: DraftUnit };

const snap = (value: number) => Math.max(0, Math.round(value / 10) * 10);
const freshId = () => `draft-${crypto.randomUUID()}`;
const elementDefaults: Record<Exclude<ElementType, "UNIT">, Pick<CanvasElement, "width" | "height" | "label">> = {
  ZONE: { width: 260, height: 180, label: "Zone" }, WALL: { width: 240, height: 14, label: "Wall" }, DOOR: { width: 70, height: 18, label: "Door" }, LABEL: { width: 180, height: 44, label: "Label" },
};

export function FacilityMapEditor() {
  const [facilities, setFacilities] = useState<Facility[]>([]); const [facilityId, setFacilityId] = useState(""); const [floorName, setFloorName] = useState("");
  const [elements, setElements] = useState<CanvasElement[]>([]); const [canvasSize, setCanvasSize] = useState({ width: 1200, height: 720 }); const [selectedId, setSelectedId] = useState("");
  const [zoom, setZoom] = useState(.8); const [unitDialog, setUnitDialog] = useState(false); const [dragging, setDragging] = useState(""); const [resizing, setResizing] = useState("");
  const [dirty, setDirty] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const facility = facilities.find((item) => item.id === facilityId); const selected = elements.find((item) => item.id === selectedId);
  const maps = facility?.maps ?? []; const currentMap = maps.find((map) => map.name === floorName);
  const placedUnitIds = useMemo(() => new Set(facilities.flatMap((item) => item.maps.flatMap((map) => map.elements.map((element) => element.unitId).filter(Boolean) as string[]))), [facilities]);
  const unavailableUnitIds = useMemo(() => new Set([...placedUnitIds, ...elements.flatMap((element) => element.unitId ? [element.unitId] : [])]), [placedUnitIds, elements]);

  const load = useCallback(async (preferredFacility?: string, preferredFloor?: string) => {
    const response = await fetch("/api/v1/facility-map", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) { setError(payload.error?.message ?? "Layouts could not be loaded."); return; }
    setFacilities(payload.data); const nextFacilityId = preferredFacility || facilityId || payload.data[0]?.id || ""; setFacilityId(nextFacilityId); const nextFacility = payload.data.find((item: Facility) => item.id === nextFacilityId);
    const nextFloor = preferredFloor || floorName || nextFacility?.maps[0]?.name || "Ground floor"; setFloorName(nextFloor); hydrate(nextFacility?.maps.find((map: MapRecord) => map.name === nextFloor));
  }, [facilityId, floorName]);
  useEffect(() => { let active = true; fetch("/api/v1/facility-map", { cache: "no-store" }).then(async (response) => ({ response, payload: await response.json() })).then(({ response, payload }) => { if (!active) return; if (!response.ok) { setError(payload.error?.message ?? "Layouts could not be loaded."); return; } const nextFacility: Facility | undefined = payload.data[0]; const nextFloor = nextFacility?.maps[0]?.name || "Ground floor"; setFacilities(payload.data); setFacilityId(nextFacility?.id || ""); setFloorName(nextFloor); hydrate(nextFacility?.maps[0]); }); return () => { active = false; }; }, []);

  function hydrate(map?: MapRecord) {
    setCanvasSize(map ? { width: map.width, height: map.height } : { width: 1200, height: 720 });
    setElements(map?.elements.map((element) => ({ id: element.id, unitId: element.unitId ?? undefined, type: element.type, x: element.x, y: element.y, width: element.width, height: element.height, rotation: element.rotation, label: element.label || element.unit?.number || element.type, status: element.unit?.status })) ?? []); setSelectedId(""); setDirty(false);
  }
  function selectFacility(nextId: string) { if (dirty && !confirm("Discard unsaved layout changes?")) return; const next = facilities.find((item) => item.id === nextId); const nextFloor = next?.maps[0]?.name || "Ground floor"; setFacilityId(nextId); setFloorName(nextFloor); hydrate(next?.maps[0]); }
  function selectFloor(nextFloor: string) { if (dirty && !confirm("Discard unsaved layout changes?")) return; setFloorName(nextFloor); hydrate(maps.find((map) => map.name === nextFloor)); }
  function addFloor() { const name = prompt("Name this floor or layout", `Floor ${maps.length + 1}`)?.trim(); if (!name || maps.some((map) => map.name.toLowerCase() === name.toLowerCase())) return; setFloorName(name); hydrate(); setDirty(true); }
  function addShape(type: Exclude<ElementType, "UNIT">) { const defaults = elementDefaults[type]; const element = { id: freshId(), type, x: 80, y: 80, rotation: 0, ...defaults }; setElements((items) => [...items, element]); setSelectedId(element.id); setDirty(true); }
  function patchElement(id: string, patch: Partial<CanvasElement>) { setElements((items) => items.map((item) => item.id === id ? { ...item, ...patch } : item)); setDirty(true); }
  function removeSelected() { if (!selected) return; setElements((items) => items.filter((item) => item.id !== selected.id)); setSelectedId(""); setDirty(true); }
  function placeUnit(unit: Unit | null, draft?: DraftUnit) { const label = unit?.number || draft?.number || "Unit"; const type = facility?.unitTypes.find((item) => item.id === (unit?.unitTypeId || draft?.unitTypeId)); const ratio = type?.widthMetres && type?.lengthMetres ? Number(type.widthMetres) / Number(type.lengthMetres) : 1.35; const height = 90; const element: CanvasElement = { id: freshId(), unitId: unit?.id, unit: draft, type: "UNIT", x: 100, y: 100, width: snap(Math.max(70, height * ratio)), height, rotation: 0, label, status: unit?.status || "AVAILABLE" }; setElements((items) => [...items, element]); setSelectedId(element.id); setUnitDialog(false); setDirty(true); }

  async function save() {
    if (!facilityId || !floorName) return; setBusy(true); setError(""); setNotice("");
    const response = await fetch("/api/v1/facility-map", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ facilityId, name: floorName, ...canvasSize, elements: elements.map((element) => ({ ...element, status: undefined })) }) });
    const payload = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setError(payload.error?.message ?? (response.status === 409 ? "A unit number is duplicated or already placed on another floor." : "The layout could not be saved.")); return; }
    setNotice(`${floorName} saved to ${facility?.name}.`); await load(facilityId, floorName);
  }

  return <div className="page-stack map-editor-workspace">
    <PageHeader eyebrow="Visual inventory" title="Facility map builder" description="Draw and save a separate interactive unit layout for every store and floor." action={<button className="button button-primary" onClick={save} disabled={!dirty || busy}><Save size={16}/>{busy ? "Saving…" : "Save layout"}</button>}/>
    {error ? <p className="form-error">{error}</p> : null}{notice ? <p className="form-success">{notice}</p> : null}
    <section className="panel map-editor-header"><label>Store<select value={facilityId} onChange={(event) => selectFacility(event.target.value)}>{facilities.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Floor / layout<select value={floorName} onChange={(event) => selectFloor(event.target.value)}>{maps.map((map) => <option value={map.name} key={map.id}>{map.name}</option>)}{!currentMap && floorName ? <option value={floorName}>{floorName} — unsaved</option> : null}</select></label><button className="button button-secondary" onClick={addFloor}><Plus size={15}/>Add floor</button><span className="map-save-state">{dirty ? "Unsaved changes" : currentMap ? "Saved" : "New layout"}</span></section>
    <section className="map-editor-shell"><aside className="panel map-toolbox"><h2>Toolbox</h2><Tool icon={<MousePointer2/>} label="Select"/><Tool icon={<Box/>} label="Unit" action={() => setUnitDialog(true)} draggable/><Tool icon={<SquareDashed/>} label="Zone" action={() => addShape("ZONE")} draggable/><Tool icon={<Grid3X3/>} label="Wall" action={() => addShape("WALL")} draggable/><Tool icon={<DoorOpen/>} label="Door / gate" action={() => addShape("DOOR")} draggable/><Tool icon={<Type/>} label="Label" action={() => addShape("LABEL")} draggable/><hr/><Link href="/units" className="map-tool-link"><Warehouse size={16}/>Manage unit types</Link></aside>
      <div className="panel map-stage"><div className="map-stage-toolbar"><span>{floorName || "Layout"}</span><div><button onClick={() => setZoom((value) => Math.max(.4, value - .1))}><ZoomOut size={15}/></button><b>{Math.round(zoom * 100)}%</b><button onClick={() => setZoom((value) => Math.min(1.5, value + .1))}><ZoomIn size={15}/></button></div></div><div className="map-scroll"><div className="map-canvas" style={{ width: canvasSize.width, height: canvasSize.height, transform: `scale(${zoom})`, transformOrigin: "top left" }} onClick={() => setSelectedId("")} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { const type = event.dataTransfer.getData("application/map-tool") as ElementType; if (type === "UNIT") setUnitDialog(true); else if (type) addShape(type); }}>
        {elements.map((element) => <div key={element.id} className={`map-editor-element map-editor-${element.type.toLowerCase()} ${selectedId === element.id ? "selected" : ""} ${element.status ? `map-status-${element.status.toLowerCase()}` : ""}`} style={{ left: element.x, top: element.y, width: element.width, height: element.height, transform: `rotate(${element.rotation}deg)` }} onClick={(event) => { event.stopPropagation(); setSelectedId(element.id); }} onPointerDown={(event) => { if ((event.target as HTMLElement).classList.contains("map-resize-handle")) return; setDragging(element.id); event.currentTarget.setPointerCapture(event.pointerId); }} onPointerMove={(event) => { if (dragging === element.id && event.buttons) patchElement(element.id, { x: snap(element.x + event.movementX / zoom), y: snap(element.y + event.movementY / zoom) }); }} onPointerUp={() => setDragging("")}><span>{element.label}</span>{element.type === "UNIT" ? <small>{element.status?.toLowerCase()}</small> : null}<i className="map-resize-handle" onPointerDown={(event) => { event.stopPropagation(); setResizing(element.id); event.currentTarget.setPointerCapture(event.pointerId); }} onPointerMove={(event) => { if (resizing === element.id && event.buttons) patchElement(element.id, { width: Math.max(30, snap(element.width + event.movementX / zoom)), height: Math.max(20, snap(element.height + event.movementY / zoom)) }); }} onPointerUp={() => setResizing("")}/></div>)}
        {!elements.length ? <div className="map-canvas-empty"><Grid3X3 size={35}/><strong>Start building {floorName}</strong><p>Drag a tool here or click Unit, Zone, Wall, Door or Label.</p></div> : null}</div></div></div>
      <aside className="panel map-properties"><h2>Properties</h2>{selected ? <><label>Label<input value={selected.label} onChange={(event) => patchElement(selected.id, { label: event.target.value })}/></label><div className="map-property-grid"><label>X<input type="number" value={selected.x} onChange={(event) => patchElement(selected.id, { x: snap(Number(event.target.value)) })}/></label><label>Y<input type="number" value={selected.y} onChange={(event) => patchElement(selected.id, { y: snap(Number(event.target.value)) })}/></label><label>Width<input type="number" value={selected.width} onChange={(event) => patchElement(selected.id, { width: Math.max(10, Number(event.target.value)) })}/></label><label>Height<input type="number" value={selected.height} onChange={(event) => patchElement(selected.id, { height: Math.max(10, Number(event.target.value)) })}/></label></div>{selected.type === "UNIT" ? <p className="map-property-note"><Tag size={14}/>{selected.status || "Draft unit"}</p> : null}<button className="button button-danger" onClick={removeSelected}><Trash2 size={15}/>Remove from layout</button></> : <div className="empty-cell">Select an element to edit its size, position and label.</div>}</aside>
    </section>{unitDialog && facility ? <UnitPlacementDialog facility={facility} placedUnitIds={unavailableUnitIds} floorName={floorName} draftNumbers={elements.flatMap((element) => element.unit ? [element.unit.number] : [])} close={() => setUnitDialog(false)} place={placeUnit}/> : null}
  </div>;
}

function Tool({ icon, label, action, draggable }: { icon: React.ReactNode; label: string; action?: () => void; draggable?: boolean }) { return <button type="button" onClick={action} draggable={draggable} onDragStart={(event) => event.dataTransfer.setData("application/map-tool", label === "Door / gate" ? "DOOR" : label.toUpperCase())}>{icon}<span>{label}</span></button>; }

function UnitPlacementDialog({ facility, placedUnitIds, floorName, draftNumbers, close, place }: { facility: Facility; placedUnitIds: Set<string>; floorName: string; draftNumbers: string[]; close: () => void; place: (unit: Unit | null, draft?: DraftUnit) => void }) {
  const [mode, setMode] = useState<"existing" | "new">(facility.units.some((unit) => !placedUnitIds.has(unit.id)) ? "existing" : "new"); const availableUnits = facility.units.filter((unit) => !placedUnitIds.has(unit.id));
  const [error, setError] = useState("");
  function submit(form: FormData) { if (mode === "existing") { const unit = availableUnits.find((item) => item.id === form.get("unitId")); if (unit) place(unit); return; } const number = String(form.get("number")).trim(); if (facility.units.some((unit) => unit.number.toLowerCase() === number.toLowerCase()) || draftNumbers.some((item) => item.toLowerCase() === number.toLowerCase())) { setError(`Unit number ${number} already exists or is already waiting to be saved.`); return; } place(null, { unitTypeId: String(form.get("unitTypeId")), number, floor: floorName, zone: String(form.get("zone") || "") || undefined, monthlyRate: Number(form.get("monthlyRate")), taxRate: Number(form.get("taxRate") || 15) / 100 }); }
  return <div className="modal-backdrop"><div className="modal-card map-unit-modal"><button className="modal-close" onClick={close}><X size={18}/></button><p className="eyebrow">Map unit</p><h2>Place a unit</h2><div className="map-unit-tabs"><button className={mode === "existing" ? "active" : ""} onClick={() => { setMode("existing"); setError(""); }} disabled={!availableUnits.length}>Existing unit</button><button className={mode === "new" ? "active" : ""} onClick={() => { setMode("new"); setError(""); }}>Create new unit</button></div><form action={submit} className="inventory-form">{mode === "existing" ? <label className="inventory-form-wide">Available unit<select name="unitId" required>{availableUnits.map((unit) => <option value={unit.id} key={unit.id}>{unit.number} · {unit.unitType.name} · {unit.status}</option>)}</select></label> : facility.unitTypes.length ? <><label>Unit type<select name="unitTypeId" required>{facility.unitTypes.map((type) => <option value={type.id} key={type.id}>{type.name}</option>)}</select></label><label>Unit number<input name="number" required/></label><label>Zone / section<input name="zone"/></label><label>Monthly rate (R)<input name="monthlyRate" type="number" min="0" step=".01" required/></label><label>VAT rate (%)<input name="taxRate" type="number" defaultValue="15" step=".01"/></label></> : <p className="form-error inventory-form-wide">Create at least one unit type before placing units. <Link href="/units">Open Units & Availability</Link>.</p>}{error ? <p className="form-error inventory-form-wide">{error}</p> : null}<div className="form-actions inventory-form-wide"><button type="button" className="button button-secondary" onClick={close}>Cancel</button><button className="button button-primary" disabled={mode === "new" && !facility.unitTypes.length}>Place unit</button></div></form></div></div>;
}
